org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=37

# IPv6 is broken on this machine (Maven/Crashlytics symbol upload need IPv4)
systemProp.java.net.preferIPv4Stack=true
